name: Delete Tag
author: Tanyi Chen
description: Delete a tag with associated release
inputs:
  tag:
    description: Tag name for deleting
    required: true
  token:
    description: Github token
    default: ${{ github.token }}
  keep_release:
    description: Don't delete release
  ignore_error:
    description: Ignore error when deleting tag
runs:
  using: composite
  steps:
    - name: Delete Tag
      run: |
        if [[ -z "${{ inputs.keep_release }}" ]]; then ${GITHUB_ACTION_PATH}/delete_release.py; fi
        git status || git init
        git push https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY} :${TAG} \
          || if [[ -z "${IGNORE_ERROR}" ]]; then exit 1; fi
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        IGNORE_ERROR: ${{ inputs.ignore_error }}
        TAG: ${{ inputs.tag }}